import streamlit as st, pandas as pd, plotly.express as px, plotly.graph_objects as go
st.set_page_config(page_title="arcAI Sections", layout="wide")
st.title("arcAI Section Picker Dashboard")

csv = st.file_uploader("Upload sections_summary.csv or *_summary.csv", type=["csv"])
if not csv:
    st.info("Upload a CSV generated by section_picker.py"); st.stop()

df = pd.read_csv(csv)
st.dataframe(df.head(50), use_container_width=True)

if {"section_index","fish_count"}.issubset(df.columns):
    g = df.groupby("section_index")["fish_count"].max().reset_index()
    fig = go.Figure(go.Bar(x=g["section_index"], y=g["fish_count"]))
    fig.update_layout(title="Max fish per 10-min section", xaxis_title="Section", yaxis_title="Fish")
    st.plotly_chart(fig, use_container_width=True)

if {"timestamp_s","fish_count"}.issubset(df.columns):
    df2 = df.sort_values("timestamp_s")
    st.plotly_chart(px.line(df2, x="timestamp_s", y="fish_count",
                            title="Fish density over time"), use_container_width=True)
